---
region: 'us-east-1'
az:
  - { name: 'a', cidr: '10.20.127.16/28' }

vpc_id: 
ansible_key_name: ansible_key
bastion_key_name: bastion_key
instance_type: t2.micro
image_id: ami-00874d747dde814fa # Ubuntu 22.04